"use client";

import { useState } from 'react'
import Link from 'next/link'
import Nav from '@/components/Nav'
import LessonContent from '../../components/LessonContent'
import VoiceChat from '../../components/VoiceChat'
import VideoFeed from '../../components/VideoFeed'

export default function LessonPage({
  params,
}: {
  params: { subjectId: string; chapterId: string };
}) {
  const [showSidebar, setShowSidebar] = useState(true)

  // Demo lesson data — in production this comes from the API
  const lesson = {
    title: `Chapter ${params.chapterId}`,
    contentHtml: '<p>This lesson content is generated by the AI tutor based on your learning level and preferences. Ask questions using the chatbot or voice tutor to deepen your understanding.</p>',
    diagrams: [] as string[],
    formulas: [] as string[],
    keyConcepts: ['Key Concept 1', 'Key Concept 2', 'Key Concept 3'],
    summary: 'This chapter covers the fundamental concepts. Complete the activity at the end to test your understanding.',
  }

  return (
    <>
      <Nav />
      <main className="min-h-screen bg-dark">
        <div className="border-b border-white/5 bg-dark-100/80 backdrop-blur-xl px-6 py-3 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Link href={`/learn/${params.subjectId}`} className="text-sm text-accent hover:text-accent-hover">&larr; Back</Link>
            <h1 className="text-lg font-semibold text-white">{lesson.title}</h1>
          </div>
          <div className="flex items-center gap-2">
            <button
              onClick={() => setShowSidebar(!showSidebar)}
              className="text-sm px-3 py-1.5 border border-white/5 rounded-lg text-white/40 hover:bg-white/5 transition-colors"
            >
              {showSidebar ? 'Hide' : 'Show'} Sidebar
            </button>
            <Link
              href={`/learn/${params.subjectId}/${params.chapterId}/activity`}
              className="text-sm px-4 py-1.5 bg-accent text-white rounded-lg hover:bg-accent-hover transition-colors"
            >
              Activity &rarr;
            </Link>
          </div>
        </div>

        <div className="flex">
          {/* Main content area */}
          <div className={`flex-1 p-6 md:p-10 ${showSidebar ? 'max-w-3xl' : 'max-w-4xl mx-auto'}`}>
            <LessonContent {...lesson} />
          </div>

          {/* Right sidebar: Voice + Video */}
          {showSidebar && (
            <aside className="w-80 border-l border-white/5 bg-dark-100/60 p-4 space-y-4 hidden lg:block">
              <VideoFeed />
              <VoiceChat />
            </aside>
          )}
        </div>
      </main>
    </>
  );
}
